# Generated by Django 6.0.4 on 2026-04-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierReinscription",
            fields=[
                ("idDossier", models.AutoField(primary_key=True, serialize=False)),
                ("dateCreation", models.DateTimeField(auto_now_add=True)),
                (
                    "statusVisite",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                (
                    "statusValidation",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                (
                    "statusPaiement",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("datePaiement", models.DateTimeField(blank=True, null=True)),
                ("montant", models.FloatField(default=0.0)),
                ("operateur", models.CharField(blank=True, max_length=50)),
                (
                    "etudiant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossier",
                        to="users.etudiant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                ("idNotification", models.AutoField(primary_key=True, serialize=False)),
                ("emetteur", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("dateEnvoie", models.DateTimeField(auto_now_add=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="users.etudiant",
                    ),
                ),
            ],
        ),
    ]
