# Generated by Django 6.0.4 on 2026-04-18 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscriptions", "0002_notifications_lu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifications",
            name="etudiant",
        ),
        migrations.AddField(
            model_name="notifications",
            name="destinataire",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notifications",
            name="type_cible",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
