# Generated by Django 6.0.4 on 2026-04-18 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscriptions", "0003_remove_notifications_etudiant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notifications",
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.RenameField(
            model_name="notifications",
            old_name="dateEnvoie",
            new_name="date_envoi",
        ),
        migrations.RenameField(
            model_name="notifications",
            old_name="idNotification",
            new_name="id_notification",
        ),
        migrations.AddField(
            model_name="notifications",
            name="filtre_annee",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="notifications",
            name="filtre_departement",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="notifications",
            name="filtre_filiere",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="notifications",
            name="filtre_niveau",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="notifications",
            name="filtre_role",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="notifications",
            name="filtre_ufr",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="destinataire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="type_cible",
            field=models.CharField(
                choices=[
                    ("TOUS", "Tous les utilisateurs"),
                    ("ROLE", "Par rôle"),
                    ("CLASSE", "Par classe académique"),
                    ("INDIVIDUEL", "Utilisateur spécifique"),
                ],
                max_length=20,
            ),
        ),
    ]
