# Generated by Django 6.0.4 on 2026-04-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inscriptions", "0004_alter_notifications_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notifications",
            options={},
        ),
        migrations.RenameField(
            model_name="notifications",
            old_name="date_envoi",
            new_name="dateEnvoie",
        ),
        migrations.RenameField(
            model_name="notifications",
            old_name="id_notification",
            new_name="idNotification",
        ),
    ]
