# Generated by Django 6.0.3 on 2026-04-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentscolarite',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='bibliothecaire',
            name='numero_employe',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='specialite',
        ),
    ]
