# Generated by Django 6.0.4 on 2026-04-11 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_agentscolarite_bureau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationBibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('en_regle', models.BooleanField(default=False)),
                ('bibliothecaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='users.bibliothecaire')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_bibliotheque', to='users.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='VisiteMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField()),
                ('resultat', models.TextField(blank=True)),
                ('aptitude', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites_medicales', to='users.etudiant')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='users.medecin')),
            ],
        ),
    ]
