# Generated by Django 6.0.3 on 2026-04-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='method',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('card', 'Card'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='paytech_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
