# Generated by Django 6.0.4 on 2026-04-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_paiement_id_alter_validationbibliotheque_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="validationbibliotheque",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="visitemedicale",
            name="date_visite",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="visitemedicale",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
