# Generated by Django 5.2.13 on 2026-04-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_paiement_id_alter_validationbibliotheque_id_and_more'),
        ('users', '0004_alter_agentscolarite_id_alter_bibliothecaire_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='validationbibliotheque',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitemedicale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PlanningVisiteMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings_visites', to='users.classe')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='users.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='CreneauVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_groupe', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('etudiants', models.ManyToManyField(blank=True, related_name='creneaux_visites', to='users.etudiant')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='services.planningvisitemedicale')),
            ],
            options={
                'ordering': ['numero_groupe'],
            },
        ),
    ]
