# Generated by Django 6.0.4 on 2026-04-18 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_paiement_id_alter_validationbibliotheque_id_and_more'),
        ('users', '0004_alter_agentscolarite_id_alter_bibliothecaire_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='validationbibliotheque',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitemedicale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CreneauVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufr', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='users.medecin')),
            ],
        ),
    ]
